### ISSUE TITLE
What is the name of this algorithm

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/sorting-assignment-merijng#1]
I would like to know the name of this sorting algorithm. Can you find a reference to a description of this algorithm?

**Comment by merijng** [comment]
Deze algoritme heet Bubble Sort.

**Comment by merijng** [comment]
@dvberkel ,

Zie bovenstaande comment.

**Comment by merijng** [comment]
Bij deze sluit ik dit issue, gezien de vraag beantwoord is.
