### ISSUE TITLE
How do you know this algorithm works

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/sorting-assignment-merijng#2]
How do I know that this algorithm works?

**Comment by merijng** [comment]
@dvberkel ,

Je kan de volgende test gebruiken. Zorg ervoor dat de sort functionaliteit in dezelfde class zit.

C# CODE:

List<int> unsorted = new List<int>() {
                4,
                2,
                6,
                -2
            };

            var sortedList = Sort(unsorted);

            if (sortedList[0] != -2)
                throw new Exception("Expected first value to be -2");

            if (sortedList[1] != 2)
                throw new Exception("Expected second value to be 2");

            if (sortedList[2] != 4)
                throw new Exception("Expected third value to be 4");

            if (sortedList[3] != 6)
                throw new Exception("Expected last value to be 6");

**Comment by merijng** [comment]
@dvberkel ,

De test is momenteel wel aangeleverd (en staat dus niet alleen in dit issue)

Concreet antwoord:
De assignment is aangemaakt in de klas. Hiervoor was slechts een beperkte tijd voor beschikbaar. Bovendien was dit assignment in mijn ogen bedoeld om aan te tonen dat er een sort algoritme gemaakt kan worden zonder gebruik te maken van de ingebouwde feature .sort() (of verwanten ervan).

Als ontwikkelaar heb ik middels debugging geconstateerd dat de functie werkt.

Hiermee kan denk ik dit issue worden gesloten, gezien uw vragen beantwoord zijn. Mochten er meer vragen en/of opmerkingen zijn dan zie ik graag een nieuwe issue.
